services:
  vinyl-vision:
    build: .
    network_mode: host
    volumes:
      - ./catalog:/app/catalog
      - ./images:/app/images
    environment:
      - DISCOGS_TOKEN=${DISCOGS_TOKEN}
      - HF_TOKEN=${HF_TOKEN}
